# Generated by Django 4.1.1 on 2022-09-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_yello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='username',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
