# Generated by Django 4.1.1 on 2022-09-16 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_yello', '0005_comment_likes_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commenenter_name',
            new_name='commenter_name',
        ),
    ]
